apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-test
  name: frontend-test
  namespace: inpt
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-test
