apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: backend-image-automation
  namespace: flux-system
spec:
  sourceRef: # moved from `.spec.checkout`
    kind: GitRepository
    name: gitopsrepo
  git:
    checkout:
      ref:
        branch: Solution
    commit:
      author:
        email: fluxcdbot@test.me
        name: fluxcdbot
      messageTemplate: |
        Demo Cluster: An automated update from FluxBot

        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  interval: 1m0s
  update:
    strategy: Setters
    path: ./synced ## The folder you want to be synced ./synced
