apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: backend-image-automation
  namespace: flux-system
spec:
  sourceRef: # moved from `.spec.checkout`
    kind: GitRepository
    name: gitopsrepo
  git:
    checkout:
      ref:
        branch: rehearse
    commit:
      author:
        email: fluxcdbot@elham.sa
        name: fluxcdbot
      messageTemplate: |
        Demo Cluster: An automated update from FluxBot
        
        Images:
        {{ range .Updated.Images -}}
        - {{.}}
        {{ end -}}
  interval: 1m0s
  update:
    strategy: Setters
    path: ./synched
