apiVersion: v1
kind: Service
metadata:
  name: movies-backend-service
  namespace: movies
spec:
  selector:
    app: movies-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
